// Katalog resmi HARAKA SEED: 38 varietas, disalin dari benih-haraka-website/src/data/products.ts
// (Katalog Benih HARAKA SEED edisi 2025). Foto kemasan ada di public/products/<nomor>.png.
// packSize kosong & price 0 = belum diisi; lengkapi lewat menu Produk.

export type CatalogItem = {
  sku: string;
  name: string;
  crop: string;
  category: string;
  seedType: string;
  packSize: string;
  price: number;
  minStock: number;
  description: string;
  harvestAge: string;
  yieldPotential: string;
  fruitWeight: string;
  image: string;
};

export const CATALOG: CatalogItem[] = [
  {
    "sku": "HKS-KNT-50",
    "name": "KENTA F1",
    "crop": "Semangka Non Biji",
    "category": "Buah",
    "seedType": "F1 Hibrida",
    "packSize": "50 butir",
    "price": 185000,
    "minStock": 200,
    "description": "Semangka tanpa biji untuk dataran rendah dengan buah bulat, kulit hijau tua bergaris hijau keabu-abuan. Daging buah merah yang manis tidak mudah pecah dan memiliki daya simpan yang baik.",
    "harvestAge": "55–58 hari",
    "yieldPotential": "23–29 ton/ha",
    "fruitWeight": "",
    "image": "/products/13.png"
  },
  {
    "sku": "HKS-DRA-10",
    "name": "DIARA F1",
    "crop": "Melon Daging Orange",
    "category": "Buah",
    "seedType": "F1 Hibrida",
    "packSize": "10 g",
    "price": 165000,
    "minStock": 200,
    "description": "Melon dataran rendah yang tahan virus gemini, dengan jaring tebal dan halus serta daging oranye yang manis (10,8–12,2 Brix).",
    "harvestAge": "66–68 hari",
    "yieldPotential": "54–64 ton/ha",
    "fruitWeight": "2.1–2.5 kg",
    "image": "/products/24.png"
  },
  {
    "sku": "HKS-RAINA",
    "name": "RAINA F1",
    "crop": "Melon Daging Putih",
    "category": "Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Melon dataran rendah yang tahan virus gemini, dengan jaring rapat serta daging putih kehijauan yang manis (10,5–12 Brix).",
    "harvestAge": "56–58 hari",
    "yieldPotential": "27–33 ton/ha",
    "fruitWeight": "1.9–2.2 kg",
    "image": "/products/22.png"
  },
  {
    "sku": "HKS-CLM-5",
    "name": "CALLINA MADU",
    "crop": "Pepaya Unggul",
    "category": "Buah",
    "seedType": "OP",
    "packSize": "5 g",
    "price": 55000,
    "minStock": 150,
    "description": "Pepaya dataran rendah dengan daging oranye pekat yang manis (10–12 Brix) dan bobot buah 1,2–1,3 kg.",
    "harvestAge": "8–9 bulan",
    "yieldPotential": "69–79 ton/ha",
    "fruitWeight": "",
    "image": "/products/12.png"
  },
  {
    "sku": "HKS-BELVA",
    "name": "BELVA",
    "crop": "Blewah Unggul",
    "category": "Buah",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Blewah dataran rendah dengan daging oranye yang lembut dan manis serta alur lebar pada buah berbentuk lonjong.",
    "harvestAge": "48–50 hari",
    "yieldPotential": "13–18 ton/ha",
    "fruitWeight": "1.2–1.6 kg",
    "image": "/products/33.png"
  },
  {
    "sku": "HKS-BNT-10",
    "name": "BIANTARA F1",
    "crop": "Cabai Keriting",
    "category": "Cabai",
    "seedType": "F1 Hibrida",
    "packSize": "10 g",
    "price": 145000,
    "minStock": 400,
    "description": "Hibrida dataran rendah–menengah dengan buah merah panjang agak keriting dan rasa pedas; hingga 187–198 buah per tanaman.",
    "harvestAge": "86–91 hari",
    "yieldPotential": "24–29 ton/ha",
    "fruitWeight": "",
    "image": "/products/21.png"
  },
  {
    "sku": "HKS-BESARI",
    "name": "BESARI",
    "crop": "Cabai Rawit Dompolan Putih",
    "category": "Cabai",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Cabai rawit dataran rendah dengan buah kuning kehijauan berbentuk kerucut yang tumbuh bergerombol lebat (168–189 buah per tanaman).",
    "harvestAge": "79–87 hari",
    "yieldPotential": "9–12 ton/ha",
    "fruitWeight": "",
    "image": "/products/25.png"
  },
  {
    "sku": "HKS-ORIMA",
    "name": "ORIMA",
    "crop": "Cabai Rawit Dompolan Putih",
    "category": "Cabai",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Cabai rawit dataran rendah dengan buah segitiga sedang yang matang oranye kemerahan, tumbuh bergerombol lebat (280–320 buah per tanaman).",
    "harvestAge": "97–102 hari",
    "yieldPotential": "8–10 ton/ha",
    "fruitWeight": "",
    "image": "/products/38.png"
  },
  {
    "sku": "HKS-PITHA",
    "name": "PITHA",
    "crop": "Cabai Rawit Putih Tegak",
    "category": "Cabai",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Cabai rawit dataran rendah yang sangat produktif dengan buah tegak berubah dari kuning kehijauan menjadi merah; 312–349 buah per tanaman.",
    "harvestAge": "84–89 hari",
    "yieldPotential": "15–19 ton/ha",
    "fruitWeight": "",
    "image": "/products/26.png"
  },
  {
    "sku": "HKS-GANNA",
    "name": "GANNA",
    "crop": "Cabai Rawit Prentul Putih",
    "category": "Cabai",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Cabai rawit dataran rendah dengan buah berubah dari putih menjadi merah tua; 160–181 buah per tanaman.",
    "harvestAge": "89–95 hari",
    "yieldPotential": "10–12 ton/ha",
    "fruitWeight": "",
    "image": "/products/27.png"
  },
  {
    "sku": "HKS-GHAHAR",
    "name": "GHAHAR",
    "crop": "Cabai Rawit Hijau Tegak",
    "category": "Cabai",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Beradaptasi dari dataran rendah hingga dataran tinggi; buah hijau cerah mengilap menjadi merah, tahan layu bakteri dan berumur genjah.",
    "harvestAge": "71–75 hari",
    "yieldPotential": "9–13 ton/ha",
    "fruitWeight": "",
    "image": "/products/28.png"
  },
  {
    "sku": "HKS-GAJO",
    "name": "GAJO",
    "crop": "Cabai Rawit Hijau Merunduk",
    "category": "Cabai",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Cabai rawit dataran rendah–menengah dengan tipe tumbuh tegak dan rimbun; buah 6–11 cm yang keras dan sangat pedas, matang dari hijau menjadi merah.",
    "harvestAge": "± 90 hari",
    "yieldPotential": "± 1.2 kg/tanaman",
    "fruitWeight": "",
    "image": "/products/31.png"
  },
  {
    "sku": "HKS-SHW-10",
    "name": "SAHWA F1",
    "crop": "Tomat Sayur Dataran Rendah",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "10 g",
    "price": 135000,
    "minStock": 250,
    "description": "Tomat determinate dataran rendah–menengah yang tahan layu bakteri dan virus gemini, dengan buah manis-asam berbobot 60–77 g.",
    "harvestAge": "",
    "yieldPotential": "45–56 ton/ha",
    "fruitWeight": "",
    "image": "/products/6.png"
  },
  {
    "sku": "HKS-NURA",
    "name": "NURA F1",
    "crop": "Tomat Buah Dataran Tinggi",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Tomat indeterminate dataran tinggi yang tahan layu bakteri dan virus gemini, dengan buah manis-asam berbobot 100–120 g.",
    "harvestAge": "60–65 hari",
    "yieldPotential": "60–70 ton/ha",
    "fruitWeight": "",
    "image": "/products/7.png"
  },
  {
    "sku": "HKS-BIUTI",
    "name": "BIUTI",
    "crop": "Terong Apel",
    "category": "Sayuran Buah",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Terung dataran rendah dengan kulit hijau bersemburat ungu, kandungan antosianin tinggi, dan daging putih kehijauan yang agak manis.",
    "harvestAge": "45–48 hari",
    "yieldPotential": "25–30 ton/ha",
    "fruitWeight": "",
    "image": "/products/8.png"
  },
  {
    "sku": "HKS-RAJENDRA",
    "name": "RAJENDRA",
    "crop": "Terong Lalap",
    "category": "Sayuran Buah",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Terung dataran rendah–menengah yang vigor dengan buah hijau bergaris dan daging putih kehijauan yang agak manis.",
    "harvestAge": "49–51 hari",
    "yieldPotential": "13–14 ton/ha",
    "fruitWeight": "",
    "image": "/products/9.png"
  },
  {
    "sku": "HKS-JNU-10",
    "name": "JANU F1",
    "crop": "Terong Ungu",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "10 g",
    "price": 75000,
    "minStock": 250,
    "description": "Hibrida dataran rendah–menengah yang vigor dengan buah ungu tua mengilap berbobot 158–212 g; 18–24 buah per tanaman.",
    "harvestAge": "56–59 hari",
    "yieldPotential": "71–83 ton/ha",
    "fruitWeight": "",
    "image": "/products/10.png"
  },
  {
    "sku": "HKS-VIONEX",
    "name": "VIONEX F1",
    "crop": "Terong Ungu",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Terung ungu hibrida dataran rendah–menengah yang vigor dengan percabangan produktif, kulit ungu mengkilap dan daging manis; 21–26 buah per tanaman.",
    "harvestAge": "55–58 hari",
    "yieldPotential": "47–60 ton/ha",
    "fruitWeight": "",
    "image": "/products/37.png"
  },
  {
    "sku": "HKS-LAKSITA",
    "name": "LAKSITA F1",
    "crop": "Terong Hijau",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Hibrida dataran rendah–menengah yang vigor dan bercabang banyak dengan kulit hijau mengilap, tahan layu bakteri.",
    "harvestAge": "52–56 hari",
    "yieldPotential": "65–80 ton/ha",
    "fruitWeight": "",
    "image": "/products/11.png"
  },
  {
    "sku": "HKS-VIVAN",
    "name": "VIVAN F1",
    "crop": "Mentimun Lalap Hibrida",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Hibrida dataran rendah yang tahan virus gemini dan embun bulu; buah hijau bergaris samar, tidak pahit (126–163 g).",
    "harvestAge": "29–32 hari",
    "yieldPotential": "40–45 ton/ha",
    "fruitWeight": "",
    "image": "/products/14.png"
  },
  {
    "sku": "HKS-CAMAL",
    "name": "CAMAL F1",
    "crop": "Mentimun Rujak Hibrida",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Hibrida dataran rendah dengan buah hijau tua berujung lebih terang, tidak pahit (230–255 g) dan daya simpan unggul 13–14 hari.",
    "harvestAge": "31–35 hari",
    "yieldPotential": "39–51 ton/ha",
    "fruitWeight": "",
    "image": "/products/15.png"
  },
  {
    "sku": "HKS-MEI-25",
    "name": "MEILI F1",
    "crop": "Mentimun Lalap Hibrida",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "25 g",
    "price": 85000,
    "minStock": 300,
    "description": "Beradaptasi dari dataran rendah hingga dataran tinggi; vigor dan bercabang banyak, tahan virus gemini dan embun bulu, dengan buah hijau tua yang tidak pahit.",
    "harvestAge": "31–35 hari",
    "yieldPotential": "25–31 ton/ha",
    "fruitWeight": "",
    "image": "/products/16.png"
  },
  {
    "sku": "HKS-VDA-25",
    "name": "VEDA F1",
    "crop": "Pare Unggul",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "25 g",
    "price": 70000,
    "minStock": 200,
    "description": "Beradaptasi dari dataran rendah hingga dataran tinggi; buah silindris hijau muda berbobot 282–322 g, 12–14 buah per tanaman.",
    "harvestAge": "43–46 hari",
    "yieldPotential": "32–34 ton/ha",
    "fruitWeight": "",
    "image": "/products/17.png"
  },
  {
    "sku": "HKS-KANAYA",
    "name": "KANAYA F1",
    "crop": "Paria Unggul",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Paria dataran rendah yang vigor dan tumbuh seragam, tahan terhadap penyakit kresek, dengan bobot buah 237–283 g; 10–14 buah per tanaman.",
    "harvestAge": "43–45 hari",
    "yieldPotential": "43–51 ton/ha",
    "fruitWeight": "237–283 g",
    "image": "/products/36.png"
  },
  {
    "sku": "HKS-GANTA",
    "name": "GANTA",
    "crop": "Timun Suri Kuning",
    "category": "Sayuran Buah",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Varietas dataran rendah yang sangat produktif, matang menjadi kuning dengan daging oranye pucat yang agak manis; buah 1,07–1,51 kg.",
    "harvestAge": "± 50 hari",
    "yieldPotential": "40–49 ton/ha",
    "fruitWeight": "",
    "image": "/products/23.png"
  },
  {
    "sku": "HKS-HANASTA",
    "name": "HANASTA F1",
    "crop": "Oyong Hibrida",
    "category": "Sayuran Buah",
    "seedType": "F1 Hibrida",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Hibrida dataran rendah yang produktif dengan percabangan kokoh dan buah hijau tua yang tidak pahit; 15–18 buah per tanaman.",
    "harvestAge": "34–37 hari",
    "yieldPotential": "38–42 ton/ha",
    "fruitWeight": "",
    "image": "/products/34.png"
  },
  {
    "sku": "HKS-VALLEN",
    "name": "VALLEN",
    "crop": "Bayam Hijau Unggul",
    "category": "Sayuran Daun",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Bayam dataran rendah–menengah dengan daun hijau muda yang lembut, manis, tanpa serat, dan tipe tumbuh tegak.",
    "harvestAge": "20–30 hari",
    "yieldPotential": "10–15 ton/ha",
    "fruitWeight": "",
    "image": "/products/2.png"
  },
  {
    "sku": "HKS-SAFIA",
    "name": "SAFIA",
    "crop": "Kangkung Daun Sedang",
    "category": "Sayuran Daun",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Kangkung dataran rendah–menengah yang vigor dan seragam dengan batang kokoh, lambat berbunga, dan tahan embun tepung.",
    "harvestAge": "21–25 hari",
    "yieldPotential": "25–30 ton/ha",
    "fruitWeight": "",
    "image": "/products/1.png"
  },
  {
    "sku": "HKS-SYLVIA",
    "name": "SYLVIA",
    "crop": "Kangkung Daun Sempit",
    "category": "Sayuran Daun",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Kangkung dataran rendah–menengah yang tegak dan tidak menjalar dengan daun sempit menyerupai bambu; renyah dan agak manis, hingga 5 kali panen ulang.",
    "harvestAge": "20–25 hari",
    "yieldPotential": "",
    "fruitWeight": "",
    "image": "/products/5.png"
  },
  {
    "sku": "HKS-RIHANA",
    "name": "RIHANA",
    "crop": "Kemangi Unggul",
    "category": "Sayuran Daun",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Kemangi dataran rendah dengan daun runcing pada batang hijau kekuningan dan 15–16 cabang; harum dan tidak pahit.",
    "harvestAge": "22–23 hari",
    "yieldPotential": "4–5 ton/ha",
    "fruitWeight": "",
    "image": "/products/3.png"
  },
  {
    "sku": "HKS-SDY-25",
    "name": "SENDAYU",
    "crop": "Sawi Manis Unggul",
    "category": "Sayuran Daun",
    "seedType": "OP",
    "packSize": "25 g",
    "price": 25000,
    "minStock": 400,
    "description": "Beradaptasi dari dataran rendah hingga dataran tinggi; daun hijau cerah tanpa serat (9–10 helai per tanaman), cepat tumbuh dan mudah dirawat.",
    "harvestAge": "22–25 hari",
    "yieldPotential": "28–30 ton/ha",
    "fruitWeight": "",
    "image": "/products/4.png"
  },
  {
    "sku": "HKS-BETHARIA",
    "name": "BETHARIA",
    "crop": "Selada Unggul",
    "category": "Sayuran Daun",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Selada yang tumbuh mudah dengan daun keriting, bergelombang, dan melebar berwarna hijau cerah, membentuk crop padat dan berat. Toleransi tinggi terhadap tipburn dan tahan panas, tidak mudah berbunga pada suhu tinggi, serta dapat ditanam sepanjang tahun.",
    "harvestAge": "",
    "yieldPotential": "",
    "fruitWeight": "",
    "image": "/products/35.png"
  },
  {
    "sku": "HKS-VNT-100",
    "name": "VINETA",
    "crop": "Kacang Panjang Biji Hitam",
    "category": "Kacang-kacangan",
    "seedType": "OP",
    "packSize": "100 g",
    "price": 35000,
    "minStock": 500,
    "description": "Kacang panjang dataran rendah–menengah dengan polong hijau panjang berujung ungu, renyah dan manis; 31–36 polong per tanaman.",
    "harvestAge": "46–49 hari",
    "yieldPotential": "28–32 ton/ha",
    "fruitWeight": "",
    "image": "/products/18.png"
  },
  {
    "sku": "HKS-GANTARI",
    "name": "GANTARI",
    "crop": "Kacang Panjang Biji Merah",
    "category": "Kacang-kacangan",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Kacang panjang dataran rendah–menengah dengan polong hijau tua panjang, renyah dan manis; 36–39 polong per tanaman.",
    "harvestAge": "42–45 hari",
    "yieldPotential": "21–25 ton/ha",
    "fruitWeight": "",
    "image": "/products/19.png"
  },
  {
    "sku": "HKS-ARINA",
    "name": "ARINA",
    "crop": "Buncis Biji Coklat",
    "category": "Kacang-kacangan",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Beradaptasi dari dataran rendah hingga dataran tinggi; polong hijau tua lurus, renyah dan manis, serta sangat produktif (55–108 polong per tanaman).",
    "harvestAge": "44–46 hari",
    "yieldPotential": "21–25 ton/ha",
    "fruitWeight": "",
    "image": "/products/29.png"
  },
  {
    "sku": "HKS-LMN-250",
    "name": "LUMINA",
    "crop": "Buncis Biji Coklat Tua",
    "category": "Kacang-kacangan",
    "seedType": "OP",
    "packSize": "250 g",
    "price": 45000,
    "minStock": 300,
    "description": "Beradaptasi dari dataran rendah hingga dataran tinggi; polong hijau muda panjang dan lurus yang renyah dan bercita rasa bersih; 63–68 polong per tanaman.",
    "harvestAge": "36–38 hari",
    "yieldPotential": "19–20 ton/ha",
    "fruitWeight": "",
    "image": "/products/30.png"
  },
  {
    "sku": "HKS-MRS-250",
    "name": "MARISA F1",
    "crop": "Jagung Manis Hibrida",
    "category": "Jagung",
    "seedType": "F1 Hibrida",
    "packSize": "250 g",
    "price": 95000,
    "minStock": 300,
    "description": "Hibrida dataran rendah dengan tongkol silindris berbiji kuning rapat, manis (11,5–14 Brix); 329–448 g per tongkol.",
    "harvestAge": "75–78 hari",
    "yieldPotential": "9–12 ton/ha",
    "fruitWeight": "",
    "image": "/products/20.png"
  },
  {
    "sku": "HKS-DHITA",
    "name": "DHITA",
    "crop": "Jagung Manis OP",
    "category": "Jagung",
    "seedType": "OP",
    "packSize": "",
    "price": 0,
    "minStock": 0,
    "description": "Beradaptasi dari dataran rendah hingga dataran tinggi; tongkol sedang hingga besar dengan kelobot rapat, sangat manis, tahan kekeringan dan embun bulu.",
    "harvestAge": "± 55 hari",
    "yieldPotential": "13–15 ton/ha",
    "fruitWeight": "",
    "image": "/products/32.png"
  }
];

/**
 * Gramasi & harga per kemasan dari "PRICELIST PRODUCT HARAKA SEED 2025": nama varietas → [gram, harga][].
 * Hanya dipakai untuk mengisi awal; setelah itu gramasi & harga dikelola lewat menu Produk.
 */
export const PRICELIST: Record<string, [number, number][]> = {
  VALLEN: [[500, 40000]],
  BELVA: [[20, 25000]],
  ARINA: [[100, 10000], [500, 35000]],
  LUMINA: [[100, 10000], [500, 35000]],
  GHAHAR: [[10, 12000]],
  GANNA: [[10, 15000]],
  BESARI: [[10, 15000]],
  GAJO: [[10, 15000]],
  PITHA: [[10, 15000]],
  "BIANTARA F1": [[10, 60000]],
  "MARISA F1": [[250, 60000]],
  DHITA: [[250, 25000]],
  GANTARI: [[100, 12000], [500, 60000]],
  VINETA: [[100, 12000], [500, 60000]],
  SYLVIA: [[500, 25000]],
  SAFIA: [[500, 20000]],
  RIHANA: [[10, 10000]],
  "DIARA F1": [[5, 75000], [10, 150000]],
  "RAINA F1": [[5, 45000], [10, 90000]],
  "MEILI F1": [[20, 25000]],
  "VIVAN F1": [[20, 25000]],
  "CAMAL F1": [[20, 25000]],
  "HANASTA F1": [[10, 12000]],
  "KANAYA F1": [[10, 12000]],
  "VEDA F1": [[10, 12000]],
  "CALLINA MADU": [[1, 8000], [5, 40000], [10, 75000]],
  "KENTA F1": [[5, 23000], [20, 90000]],
  "LAKSITA F1": [[5, 20000]],
  "JANU F1": [[5, 15000]],
  RAJENDRA: [[10, 7000]],
  BIUTI: [[10, 10000]],
  GANTA: [[10, 12000]],
  "SAHWA F1": [[5, 80000]],
  "NURA F1": [[5, 55000], [10, 110000]],
  SENDAYU: [[25, 7000]],
};
